### ISSUE TITLE
geom_beeswarm() and geom_quasirandom() do not automatically dodge.

### ISSUE THREAD

**Issue by josesho** [eclarke/ggbeeswarm#11]
Load the R dataset `HairEyeColor`.

```{r}
h <- as.data.frame(HairEyeColor)
```

Standard `ggplot` solution, with automatic dodging by Sex, as desired.
```{r}
ggplot(data = h, aes(x = Eye, y = Freq, colour = Sex)) + 
   geom_point(position = position_dodge(width = 0.5))
```

Plotting with `beeswarm` package does not dodge position as expected.
```{r}
ggplot(data = h, aes(x = Eye, y = Freq, colour = Sex)) + 
   geom_beeswarm(position = position_dodge(width = 0.5))
```

**Comment by eclarke** [comment]
Thanks for the heads up. I'll try to add this behavior when I have time. Feel free to submit a pull request if you implement it beforehand.

**Comment by josesho** [comment]
Pull request submitted; let me know if there are problems! Cheers.

**Comment by eclarke** [comment]
Thanks for the pull request!
