### ISSUE TITLE
Help not working

### ISSUE THREAD

**Issue by josesho** [eclarke/ggbeeswarm#12]
Accessing the help

```{r}
?geom_beeswarm
```
produces this error message:
`Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/ggbeeswarm/help/ggbeeswarm.rdb' is corrupt `

**Comment by smsaladi** [comment]
Are you able to access help for other functions ok? `?geom_beeswarm` works for me

**Comment by josesho** [comment]
Unfortunately not; I get the same error message. Worth reinstalling?

**Comment by smsaladi** [comment]
Yeah, I'd say so. Perhaps try the other usual tricks like restarting R, clearing the environment and only loading this package, etc...?

**Comment by josesho** [comment]
Restarting R and reloading the package works. Thanks!
