### ISSUE TITLE
help with documentation/examples

### ISSUE THREAD

**Issue by hrbrmstr** [eclarke/ggbeeswarm#16]
Would you folks mind if I updated the examples with non-qplot ones? I spent alot of time helping Hadley remove the qplot examples from ggplot2-proper and we're trying to downplay (or just outright stop) it's usage. 

Also, I could add images to the actual function documentation and toss in a quick vignette.

No worries if you'd rather not have any or all of those :-)

**Comment by eclarke** [comment]
Hey, sorry for the delayed response. @sherrillmix fixed the examples on the readme and added a vignette, but we would always be happy to have more contributions!
