### ISSUE TITLE
Include Tukey's texturing method?

### ISSUE THREAD

**Issue by hadley** [eclarke/ggbeeswarm#17]
As described in:

```bib
@techreport{tukey:1990,
	Author = {Tukey, John W. and Tukey, Paul},
	Institution = {Bellcore},
	Title = {Strips displaying empirical distributions: 1. Textured dot strips},
	Year = {1990}}
```

I couldn't find a copy of the paper online, so here's a link to a scanned version I have: https://www.dropbox.com/s/frj8oxg314pcqp7/tukey-1990.pdf?dl=0

**Comment by josesho** [comment]
This looks similar to the `beeswarm` option. I suppose you mean Tukey and Tukey's constraining of the points to a fixed width all along the axis? (This seems analogous to centering a block of text vs justifying it.)

Would be interesting to implement it!

**Comment by eclarke** [comment]
Thanks @hadley for the link. I wouldn't be opposed to having such a method in the package itself instead of relying on third-parties, and Tukey included an example implementation in S so it may not be hard to adapt.

**Comment by smsaladi** [comment]
@eclarke @sherrillmix Looks like ggbeeswarm has made it into the big leagues!

**Comment by thomasjwood** [comment]
Extra vote for this feature!

**Comment by sherrillmix** [comment]
I added Tukey texturing to the [vipor package](https://github.com/sherrillmix/vipor) that does the position calculations behind the scenes. It's up on CRAN now so if you update then Tukey texturing should work with the `method='tukey'` argument e.g.:
`ggplot(iris, aes(Species, Sepal.Length)) + geom_quasirandom(method = "tukey")`
<img width="432" alt="ggplot2-methods-1" src="https://cloud.githubusercontent.com/assets/1217152/16547259/3de9edf0-4135-11e6-8c5a-3df69b2b88db.png">

**Comment by hadley** [comment]
Awesome - thanks!

**Comment by eclarke** [comment]
Thanks @sherrillmix!

**Comment by jtrim-ons** [comment]
@hadley, I'm hoping to track down the Tukey paper on textured dot strips. Your dropbox link above seems to have expired. I was wondering if you would have time to share the PDF again? No problem if not.

**Comment by hadley** [comment]
Send me an email at <hadley@posit.co> and I'll send it to you.

**Comment by jtrim-ons** [comment]
Thanks!
