### ISSUE TITLE
geom_quasirandom() does not play nicely with facets

### ISSUE THREAD

**Issue by mnbram** [eclarke/ggbeeswarm#23]
When using facet_grid() or facet_wrap() with geom_quasirandom(), the distribution of points seems to be calculated before taking into account the faceting. If factor A is stratified unevenly across a facet of factor B, then the distribution of points will reflect that for all levels of factor B, rather than for the A*B subgroup.

An example:
```
library(ggbeeswarm)

set.seed(20160824)
pop1 = rnorm(1000, 4)
pop2 = rnorm(1000, 6)

pops.df = data.frame(
  pop = factor(rep(1:2, each = 1000)),
  y = c(pop1, pop2),
  grp = rep(c("A", "B"), each = 500, times = 2)
)

ggplot(pops.df, aes(grp, y)) +
  geom_quasirandom() +
  facet_grid(.~pop)
```

This gives:
![quasi_factor](https://cloud.githubusercontent.com/assets/21060411/17938582/8199e478-69f4-11e6-816c-e1ba76eae42d.png)

The same doesn't seem to be true for geom_beeswarm(), so I assume this is not the intended behavior.

**Comment by eclarke** [comment]
Thanks for pointing this issue out. This should now be fixed in master.

**Comment by sherrillmix** [comment]
Here's a picture for proof.
`ggplot(pops.df, aes(grp, y)) + geom_quasirandom() + facet_grid(.~pop)`
![test](https://cloud.githubusercontent.com/assets/1217152/17947262/f5ffd53c-6a19-11e6-9b0a-7da5bff60d98.png)

Thanks for the clear example.
