### ISSUE TITLE
geom_beeswarm issue

### ISSUE THREAD

**Issue by jalali4** [eclarke/ggbeeswarm#26]
Thanks for this nice addition. I noticed a minor issue with the geom_beeswarm function that wanted to bring to your attention. It's probably a scaling vs width issue.

I have several hundred datapoints in the range -2000 to 6000. When I plot my datapoints using geom_beeswarm() without any additional options, I get very little scatter. Visually almost all my points line up in a straight line, many of them overlapping.

When I re-scale my data to range -2 to 6 (divide by 1000), I get a nice scatter of points with appropriate width and with no overlap. It should be easy to replicate on your end, but I can send you my data values if you like.

**Comment by sherrillmix** [comment]
Minimum working example with 
```
library(ggbeeswarm)
y<-runif(1000,-2000,6000)
x<-rep(1:2,500)
#little scatter
ggplot(NULL,aes(x,y)) + geom_beeswarm()
#reasonable scatter
ggplot(NULL,aes(x,y/1000)) + geom_beeswarm()
```

As a fast alternative, geom_quasirandom appears to work fine
```
ggplot(NULL,aes(x,y)) + geom_quasirandom()
```

For debugging, beeswarm appears to work fine:
```
beeswarm(y~x)
```

**Comment by sherrillmix** [comment]
The issue should be mostly fixed with the new version. It was a problem in `beeswarm`'s `swarmx` needing the plot generated before calculating offsets. You may need to mess with the `cex` option in `geom beeswarm` to get things looking completely nice e.g. `geom_beeswarm(cex=2)`.

![test](https://cloud.githubusercontent.com/assets/1217152/20801554/5669ed00-b7b7-11e6-88f0-a6cf7393d4d6.png)

**Comment by jalali4** [comment]
Thank you so much! When will the new version be out?

**Comment by eclarke** [comment]
I'd suggest using the development version for now. We just yesterday pushed an update to CRAN before this to fix a binary incompatibility with ggplot2, and I think it's customary to not update CRAN with too many small changes (https://cran.r-project.org/submit.html). I'll probably push it again in a month or after another few bugfixes accumulate.

**Comment by eclarke** [comment]
Looks like they allowed it this time. The new version with this bugfix should be live on CRAN now.
