### ISSUE TITLE
Attempt to apply non-function

### ISSUE THREAD

**Issue by Nenuphar** [eclarke/ggbeeswarm#29]
Hello,

When trying to reproduce the examples on the Iris dataset as they appear on the Readme file, I ran into the following error:
Error in f(..., self = self) : attempt to apply non-function

I am using R 3.2.2 from RStudio 0.99.489.

**Comment by sherrillmix** [comment]
Hmm. I just ran all the README script in R 3.3.2 and didn't generate that error so that's going to be a bit hard to debug. Do you think you could narrow it down a bit with a minimum working example? Thanks.

**Comment by sherrillmix** [comment]
I'm going to close for now. Let us know if the problem reoccurs.
