### ISSUE TITLE
Warning typo for groupOnX in position-quasirandom.R

### ISSUE THREAD

**Issue by hypercompetent** [eclarke/ggbeeswarm#34]
The Warning message provided in position-quasirandom.R line 33 says to use grouponX=FALSE instead of groupOnX=FALSE. Without the capital O, grouponX doesn't work.

Thanks for the great package!

**Comment by sherrillmix** [comment]
Thanks for catching that. Should be fixed on github now and we'll get it up on CRAN in the next release.
