### ISSUE TITLE
Feature request: adding labels

### ISSUE THREAD

**Issue by corinne-riddell** [eclarke/ggbeeswarm#35]
I'd like to make a scatter plot using `geom_quasirandom` and label the points according to a third variable (here, the third variable is lab). Normally, I'd add `geom_text(aes(label = lab)` to the code below but this doesn't work since `geom_quasirandom` deviates the x value by some amount. If it's not too difficult, could this feature be added?

```
library(ggbeeswarm)
library(tidyverse)
set.seed(1)
iris.samp <- sample_n(iris, 26)
iris.samp$lab <- LETTERS
ggplot(iris.samp, aes(Species, Sepal.Length)) + 
geom_quasirandom()
```

**Comment by eclarke** [comment]
Hi @corinne-riddell, sorry for not getting back to you sooner (only 7 months late!). This is actually possible already through the use of the `position_beeswarm` option:
```r
ggplot(iris, aes(Species, Sepal.Length)) + 
  geom_quasirandom() +
  geom_label(aes(label=lab), position=position_quasirandom()) 
```

This positions the labels directly over the points, which is maybe not ideal, but the same issue and fix exists when labeling scatterplots normally, right? Generally I guess you'd just offset the labels a bit.
