### ISSUE TITLE
Register with ggplot2 extension gallery

### ISSUE THREAD

**Issue by josesho** [eclarke/ggbeeswarm#38]
It seems [trivial](https://github.com/ggplot2-exts/gallery#adding-a-ggplot2-extension) to add this extension to the [official ggplot2 extension gallery](https://www.ggplot2-exts.org/gallery/).

Happy to do this, unless someone has some spare time?

**Comment by eclarke** [comment]
Agree it should be on there, haven’t had the bandwidth to do it recently. Would be thrilled if you wanted to do it!

**Comment by josesho** [comment]
Opened a [PR](https://github.com/ggplot2-exts/gallery/pull/52). Will close this once they have accepted.

**Comment by sherrillmix** [comment]
Looks like this was added (a long time ago, just cleaning up now). Thank you.
