### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by smsaladi** [eclarke/ggbeeswarm#4]
One more thing --

Do you have a suggested citation for this work? We are about to submit a paper with a number of figures generated using ggbeeswarm.

Thanks.

**Comment by eclarke** [comment]
We are preparing a short manuscript but we don't have a citation yet. I've seen submissions that reference the github repository or package on CRAN (https://cran.r-project.org/web/packages/vipor/) if that appeals to you. 

P.S. it'd be really cool to see the final figures once published!

**Comment by josesho** [comment]
Might be tangential, so apologise for pinging this back on. 

Any idea of the first known suggestion or implementation of the beeswarm plot in the literature? This is a matter of personal curiosity and professional courtesy (I would like to trace and cite the intellectual history, as it were, of the beeswarm plot)! 

Thanks in advance
