### ISSUE TITLE
does the ggbeeswarm package work in analyzing one-dimensional data?

### ISSUE THREAD

**Issue by ZHANGHAO007** [eclarke/ggbeeswarm#41]
Think you for your work. I wonder whether the ggbeeswarm package can be applied in exploring one-dimensional data. I want to reveal the density distribution of the data. In other words, the y value is nonexistent. I can plot the density curve with geom_density() function. Next, I want to plot a beeswarm. Can I make it?

**Comment by eclarke** [comment]
Hi there, can you post a picture or sample code to help me better understand your question?

**Comment by ZHANGHAO007** [comment]
Last week, I had solved this problem, thanks for your reply!
