### ISSUE TITLE
Feature request - alternative stacking directions

### ISSUE THREAD

**Issue by tjebo** [eclarke/ggbeeswarm#43]
See [This related stackoverflow thread](https://stackoverflow.com/questions/53697235/ggplot-dotplot-what-is-the-proper-use-of-geom-dotplot)
geom_dotplot does not allow for the plot as shown by SO user jimbou. (The plot was created by Hadley). The nice thing about this plot are the gaps between the "bins". This can only be achieved with some fanciful data preparation and geom_point. 
I think geom_beeswarm does already something very similar - but the stacking of the point is currently all centered. It would be great if one could also chose an alternative stacking direction, such as you can in `geom_dotplot(..., stackdir = "up"/ "down"/"center"/ "centerwhole"')`

**Comment by sherrillmix** [comment]
Thanks for the suggestion tjebo. The beeswarm package we're wrapping already has that functionality so I added a `beeswarmArgs` argument to `geom_beeswarm` to allow additional arguments to pass to the underlying `swarmx` function of beeswarm. You should be able to test it out from the github version of the package.

For example:

```ggplot2::qplot(class, hwy, data = ggplot2::mpg, geom='beeswarm',beeswarmArgs=list(side=1))```

![oneSided](https://user-images.githubusercontent.com/1217152/62387301-32604500-b528-11e9-8690-73bb12196199.png)

**Comment by fruttigerlab** [comment]
Awesome :) Thanks also for the swift response

**Comment by tjebo** [comment]
Awesome! Thanks also for the swift response :)

**Comment by AmeliaMN** [comment]
This doesn't seem to work anymore.

**Comment by AmeliaMN** [comment]
Ah, apologies! I see that this is deprecated, but the GitHub version has `method="center"` and `side=0`!
