### ISSUE TITLE
Cannot pass beeswarmArgs

### ISSUE THREAD

**Issue by erocoar** [eclarke/ggbeeswarm#46]
Running the example
`ggplot(iris,aes(Species, Sepal.Length)) + geom_beeswarm(beeswarmArgs=list(side=1))`
yields
`Warning: Ignoring unknown parameters: beeswarmArgs`

Any chance I am not the only one having this issue?

**Comment by kgazengel** [comment]
I'm sorry, I'm really interested in your function but I can't use beeswarmArgs parameter. I tried to re-install from devtools::install_github('eclarke/ggbeeswarm') but it's still the same. Do you have any idea of the trouble?
