### ISSUE TITLE
Incorrect documentation for position_beeswarm and position_quasirandom

### ISSUE THREAD

**Issue by KarinaMarks** [eclarke/ggbeeswarm#47]
Hello, 

Thanks for your package.

I have noticed in the documentation for the `position_*` functions that they imply the functions make violin plots. This is not true, as the `geom="violin"` or `geom_violin` determine this.

These functions are just allowing the `position` argument within other `geom_*` functions to be set as one of these `position_*` functions to offset the points/text/info to avoid overlapping. It would be useful to update the documentation to avoid confusion here.

Also, the example no longer works as mentioned in #45 the `position` argument is deprecated from `ggplot2::qplot`.

Thanks,
Karina

**Comment by eclarke** [comment]
fixed in #63
