### ISSUE TITLE
Error in ggplot(iris, aes(Species, Sepal.Length)) + geom_quasirandom() :   non-numeric argument to binary operator

### ISSUE THREAD

**Issue by fdecarpentier** [eclarke/ggbeeswarm#48]
Hi,

When i try :
`library(ggplot2)
library(ggbeeswarm)
ggplot(iris,aes(Species, Sepal.Length)) + geom_quasirandom()`

I get : 

> Error in ggplot(iris, aes(Species, Sepal.Length)) + geom_quasirandom() : 
 non-numeric argument to binary operator
    In addition: Warning message:
    Incompatible methods ("+.gg", "Ops.data.frame") for "+" 

I can't find any solution online! :( 
Is it a problem of missing library?

Thanks!

**Comment by fdecarpentier** [comment]
I solve the problem: an home made function with the same name was in the cache...

**Comment by sherrillmix** [comment]
Thanks for the update. Glad everything worked out.
