### ISSUE TITLE
Feature request - compact beeswarm

### ISSUE THREAD

**Issue by jtrim-ons** [eclarke/ggbeeswarm#62]
We recently added a new `"compactswarm"` method to the `beeswarm` package (version 0.4.0, on CRAN). We haven't yet added a vignette with nice examples, but you can see some examples in [this issue](https://github.com/aroneklund/beeswarm/issues/9). It's often seems to be quite a big improvement on `method="swarm"` As `ggbeeswarm` no longer depends on `beeswarm`, would it be worth adding an implementation of compact beeswarms?

I might have time to help with this if you think it's a good plan. An alternative would be to depend on the `beeswarm` package for compact beeswarms. (An advantage of this is that the `beeswarm` package uses a fast C implementation.)

**Comment by jtrim-ons** [comment]
@csdaw would you have any interest in having a go at this? It would be amazing if you did feel like implementing it, as you know much more about ggbeeswarm and ggplot than I do.

The R version from the beeswarm package is [here](https://github.com/aroneklund/beeswarm/blob/1db3529d3bbd1d473e044a9e706f36f310aa744c/R/beeswarm.R#L405-L460). (The default implementation is actually in C; the main part of that version is [here](https://github.com/aroneklund/beeswarm/blob/1db3529d3bbd1d473e044a9e706f36f310aa744c/src/beeswarm.c#L92-L126).)

**Comment by csdaw** [comment]
@jtrim-ons Yep I'd be happy to add the `compactswarm` method in a future PR. `ggbeeswarm` definitely still depends on `beeswarm` so it should be easy enough to incorporate this new method.

**Comment by jtrim-ons** [comment]
@csdaw amazing - thank you! Let me know if there's anything I can do to help.

It would be great if the README could include an example (or more) of the compact beeswarm after you've added the code to the package. Again, I'd be happy to help with this if you'd like me to. I think the compact swarm would improve the "With automatic dodging" example in particular.

I was also wondering about what the API might look like... I guess options include adding another parameter to `geom_beeswarm` or creating a new `geom_compactswarm` function. I don't really have an opinion about this, but it would be really nice if the existence of the compact beeswarm is made fairly obvious to users. I guess that's what the README is for!

Thanks again for offering to write the code.

**Comment by bersbersbers** [comment]
`compactswarm` has just been added to `ggbeeswarm2`, see https://github.com/csdaw/ggbeeswarm2/issues/1.
