### ISSUE TITLE
Error in .calculateSwarmUsingC: NA/NaN/Inf in foreign function call (arg 1)

### ISSUE THREAD

**Issue by bersbersbers** [eclarke/ggbeeswarm#65]
The first call works fine, the second errors with

> Saving 5.99 x 3.99 in image
Error in .calculateSwarmUsingC(xy$y, dsize = ysize * cex, gsize = xsize *  : 
  NA/NaN/Inf in foreign function call (arg 1)

```r
library(ggplot2)
ggsave("temp.png", ggplot(data.frame(x = 1, y = c(1, 2, Inf)), aes(x, y)) + geom_point())
ggsave("temp.png", ggplot(data.frame(x = 1, y = c(1, 2, Inf)), aes(x, y)) + ggbeeswarm::geom_beeswarm())
```

**Comment by jtrim-ons** [comment]
Oh no, I wrote `.calculateSwarmUsingC`! Does ggbeeswarm have an option to set `fast=False`? How does it look if you do that?

Maybe it's not so bad to throw an error instead of plotting infinity?

Sorry - just very quick thoughts!

**Comment by csdaw** [comment]
Conveniently the Github version does have the option to set `fast = FALSE` as of yesterday 😇 .

``` r
# devtools::install_github("eclarke/ggbeeswarm")
library(ggbeeswarm)
#> Loading required package: ggplot2

df <- data.frame(x = 1, y = c(1, 2, Inf))

ggplot(df, aes(x, y)) + geom_point()
```

![](https://i.imgur.com/sRLyMrV.png)

``` r
ggplot(df, aes(x, y)) + geom_beeswarm() # error
#> Error in .calculateSwarmUsingC(xy$y, dsize = ysize * cex, gsize = xsize * : NA/NaN/Inf in foreign function call (arg 1)
ggplot(df, aes(x, y)) + geom_beeswarm(fast = FALSE) # no error
```

![](https://i.imgur.com/ZKibasJ.png)

Also note that different ggplot2 functions seem to handle infinite values differently, for whatever reason.

``` r
ggplot(df, aes(x, y)) + geom_point()
```

![](https://i.imgur.com/6GwHpuI.png)

``` r
ggplot(df, aes(x, y)) + geom_jitter()
#> Warning: Removed 1 rows containing missing values (geom_point).
```

![](https://i.imgur.com/5XCvv5D.png)

``` r
ggplot(df, aes(x, y)) + geom_boxplot()
#> Warning: Removed 1 rows containing non-finite values (stat_boxplot).
```

![](https://i.imgur.com/WNcI8lt.png)

<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
