### ISSUE TITLE
new CRAN release?

### ISSUE THREAD

**Issue by kapsner** [eclarke/ggbeeswarm#74]
When will a new CRAN version be released to make changes such as the `corral`-argument for `geom_beeswarm` accessible by imports from other CRAN-packages?

**Comment by romanzenka** [comment]
I was just going to ask the same question... is there some work left over to clean up these new additions? I would appreciate new CRAN release with all the amazing new functionality!

**Comment by csdaw** [comment]
Yes this is definitely the plan at the moment. I've internally refactored `geom_beeswarm` so I'll need a bit more testing to make sure my changes are backwards compatible. I'd also like to clean up the documentation a bit and maybe add some tests. I will likely not get time to do this until December however.

**Comment by eclarke** [comment]
The new version is on CRAN as of today. Thank you for your patience!
