### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [eclarke/ggbeeswarm#75]
Hi

We are preparing the next version of ggplot2 and our reverse dependency checks show an issue with the released version of ggbeeswarm due to deprecation of `qplot()`. It appears this has already been fixed in the development version but has yet to be pushed to CRAN.

We plan to submit ggplot2 by the end of October and hope you can update ggbeeswarm before that

kind regard
Thomas

**Comment by Alanocallaghan** [comment]
Can we get a timeline on this, @eclarke ? Otherwise I'll have to remove ggbeeswarm as a dependency

**Comment by mcanouil** [comment]
The author seems to be inactive on GitHub for quite some time and did not address @thomasp85 warning in two months, so I went ahead and removed this dependency.

**Comment by eclarke** [comment]
Hi all, apologies for the non-response- I have not had time to work on this due to prior commitments, but I will be updating the package with a fix on CRAN this week.

**Comment by eclarke** [comment]
@thomasp85 @Alanocallaghan @mcanouil The new version of `ggbeeswarm` has been released and is now on CRAN. Apologies for any issues the delay here has caused.

**Comment by Alanocallaghan** [comment]
Thanks! No worries, appreciate that CRAN deadlines and real life don't always line up and the package has been super useful for me (and people who use scater)
