### ISSUE TITLE
suggesting to use Sinaplot name for function to give credit to inventors

### ISSUE THREAD

**Issue by fobinf** [eclarke/ggbeeswarm#76]
Sinaplot, part of ggforce, has been developed and maintained for many years - at the time as an alternative to beeswarm (with the branches), and well suitable for many samples. it looks like you have taken the idea also into your package, and that is great. 

The paper is here
https://www.tandfonline.com/doi/full/10.1080/10618600.2017.1366914?scroll=top&needAccess=true

the ggforce package is here (geom_sina):  https://cran.r-project.org/web/packages/ggforce/index.html 
originally from here: https://github.com/sidiropoulos/sinaplot
and as base R here: https://cran.r-project.org/web/packages/sinaplot/

I think that I am understanding that you are using the same idea, and hope that you would give credit to those first having it, by using the name that they coined, as per academic tradition.

**Comment by josesho** [comment]
Just quickly commenting here until I can find my sources, but the beewswarm plot was independently coined by another Scandinavian resesrcher (if memory serves me right), possibly around the same time as the sinaplot... I could be mistaken, but let me get back in a bit!

**Comment by josesho** [comment]
The earliest R package that implements beeswarm plots is Aron Eklund's [beeswarm](https://github.com/aroneklund/beeswarm) package, first released in July 2015.

Sidiropoulous's [earliest commit](https://github.com/sidiropoulos/sinaplot/commits/master?after=6aa060dae1889bad29cf9d37817e8e2a31284c2f+69&branch=master&qualified_name=refs%2Fheads%2Fmaster) on the sinaplot package is Sept 2015.

Eklund himself cites Leland Wilkinson's [1999 paper](https://www.cs.uic.edu/~wilkinson/Publications/dotplots.pdf) that is possibly the earliest publication suggesting the use of a density kernel to order points.

Sidiropoulous and colleagues do in face cite Eklund!

**Comment by eclarke** [comment]
Agree with @josesho on attribution timelines. Moreover, the code used for the quasirandom method (in the sherrillmix/vipor package) predates sinaplots by a number of years and does not use the same method of distributing points (c.f. van der Corput sequences). While I obviously support giving attribution to prior work, I don't believe it is relevant in this case.
