### ISSUE TITLE
Data points vertically misaligned depending on method and cex

### ISSUE THREAD

**Issue by samlin829** [eclarke/ggbeeswarm#77]
Hi - 
Just noticed that the data points move vertically depending on `cex` and `method`. It appears that this is not the case for all methods - I haven't tried all method but `swarm` seems vertically consistent regardless of the `cex` value, whereas `center`, `hex` and `square` suffer.

```
df <- data.frame(
  x = "A",
  y = sample(0:10, 100, replace = TRUE)
)

# data points do not move upwards regardless of cex
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 1, method = "swarm") + ggtitle('method = "swarm" (default)')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 3, method = "swarm") + ggtitle('method = "swarm" (default)')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 5, method = "swarm") + ggtitle('method = "swarm" (default)')

# data points move upward as cex increases
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 1, method = "center") + ggtitle('method = "center"')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 3, method = "center") + ggtitle('method = "center"')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 5, method = "center") + ggtitle('method = "center"')

# data points move upward as cex increases
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 1, method = "hex") + ggtitle('method = "hex"')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 3, method = "hex") + ggtitle('method = "hex"')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 5, method = "hex") + ggtitle('method = "hex"')

# data points move upward as cex increases
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 1, method = "square") + ggtitle('method = "square"')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 3, method = "square") + ggtitle('method = "square"')
ggplot(df, aes(x = x, y = y)) + geom_beeswarm(cex = 5, method = "square") + ggtitle('method = "square"')

```

Can someone else please verify this?

**Comment by eclarke** [comment]
Thanks for reporting. Would you be able to check if this same issue happens when using the underlying beeswarm package?

**Comment by eclarke** [comment]
@samlin829 @jtrim-ons Thanks both for looking into this. I don't have a fix planned for now since it originates in the upstream `beeswarm` package and may in fact be the intended behavior. That said, I do feel like in general a message or warning to the user when the y position changes from `position_beeswarm` may be appropriate since it's reasonable to expect it not to for these kinds of plots. I will look into adding that for the next release (right now finalizing the CRAN submission for v0.7.1).

**Comment by eclarke** [comment]
I've added a warning message to the methods that discretize the non-grouped in `position_beeswarm` alerting users that the points may shift proportional to the value of `cex`. I think that's the best we can do right now if we want to follow the same algorithms used in `beeswarm`.
