### ISSUE TITLE
Quasirandom behaves differently after update to 0.7.1

### ISSUE THREAD

**Issue by gdagstn** [eclarke/ggbeeswarm#79]
Hi,
when plotting data using `ggbeeswarm` 0.7.1 using different colors per group, it looks like the violin shape is recalculated for every color. Previously, in 0.6.0, I was able to retain a single violin shape per group, with the color changing only for the points, without recalculation.

small reprex:

```
library(ggbeeswarm)
library(ggplot2)

set.seed(10)
dat = reshape2::melt(matrix(rnorm(10000, mean = 1, sd = 1.2), ncol = 5))
types = unique(dat$Var2)
colnames(dat) = c("idx", "type", "value")
dat$type = factor(dat$type)
dat$other = dat$type
dat$other[dat$value < 0] = sapply(dat$type[dat$value < 0], function(x) sample(types[types != x], size = 1))

ggplot(dat, aes(x = type, y = value, colour = other)) + 
  geom_quasirandom(method = "smiley")
```

`ggbeeswarm 0.6.0`:

![ggbeeswarm_old](https://user-images.githubusercontent.com/21171362/212336330-ae02c848-2c3d-4f43-bf92-3d34b880b001.png)

`ggbeeswarm 0.7.1`:
![ggbeeswarm_new](https://user-images.githubusercontent.com/21171362/212336346-519ea3a8-6db3-4fe4-8031-0d071cfa878b.png)

I would like to keep the behaviour as 0.6.0, did I miss an argument or something else?

**Comment by csdaw** [comment]
Thanks for the reproducible example.  By default, the shape should _not_ be calculated for each colour unless `dodge.width` is not `NULL`. This seems to be a bug in `position_quasirandom()`, where the default value of `dodge.width` is `0` but it should be `NULL`.

https://github.com/eclarke/ggbeeswarm/blob/61271f96efa68d66c200b244efa66e320f9fc4aa/R/position-quasirandom.R#L21-L30

In the meantime you can get the old behaviour back by specifically setting `dodge.width = NULL`, re-using your example:

``` r
library(ggbeeswarm)
#> Loading required package: ggplot2
library(ggplot2)

packageVersion("ggbeeswarm")
#> [1] '0.7.1'

set.seed(10)
dat = reshape2::melt(matrix(rnorm(10000, mean = 1, sd = 1.2), ncol = 5))
types = unique(dat$Var2)
colnames(dat) = c("idx", "type", "value")
dat$type = factor(dat$type)
dat$other = dat$type
dat$other[dat$value < 0] = sapply(dat$type[dat$value < 0], function(x) sample(types[types != x], size = 1))

# default is bugged
ggplot(dat, aes(x = type, y = value, colour = other)) + 
  geom_quasirandom(method = "smiley")
```

![](https://i.imgur.com/4nq66u7.png)

``` r

# specify dodge.width = NULL to get old behaviour
ggplot(dat, aes(x = type, y = value, colour = other)) + 
  geom_quasirandom(method = "smiley", dodge.width = NULL)
```

![](https://i.imgur.com/JmOW5Ax.png)

<sup>Created on 2023-01-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gdagstn** [comment]
Great, thanks a lot!
