### ISSUE TITLE
Support beeswarm spacing parameter

### ISSUE THREAD

**Issue by FunkMonkey** [eclarke/ggbeeswarm#81]
Beeswarm [supports a spacing parameter](https://search.r-project.org/CRAN/refmans/beeswarm/html/beeswarm.html) to control the "Relative spacing between points". It would be nice if `geom_beeswarm` could forward the spacing parameter as well.

Thanks a lot!

**Comment by csdaw** [comment]
You can control the spacing with the `cex` argument. You can then increase point size using the `size` argument.

Hope this helps.

``` r
library(ggbeeswarm)
#> Loading required package: ggplot2

ggplot(ToothGrowth, aes(x = supp, y = len)) +
  geom_beeswarm() + 
  theme_bw(base_size = 14)
```

![](https://i.imgur.com/2l5HGVH.png)

``` r

ggplot(ToothGrowth, aes(x = supp, y = len)) +
  geom_beeswarm(cex = 4) + 
  theme_bw(base_size = 14)
```

![](https://i.imgur.com/zvFc1pk.png)

``` r

ggplot(ToothGrowth, aes(x = supp, y = len)) +
  geom_beeswarm(cex = 4, size = 4) + 
  theme_bw(base_size = 14)
```

![](https://i.imgur.com/y8FNd4M.png)

<sup>Created on 2023-04-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
