### ISSUE TITLE
geom_beeswarm plot error when the values of y are the same

### ISSUE THREAD

**Issue by william-swl** [eclarke/ggbeeswarm#85]
When I use `geom_beeswarm(..., method='center')` and the data have same `y` values, the function can't work normally and throw an ERROR.

Here is an minimal example:
```
mpg %>% mutate(cty=20) %>% ggplot() + geom_beeswarm(aes(x=class, y=cty), method='center')

ERROR while rich displaying an object: Error in `geom_beeswarm()`:
! Problem while computing position.
ℹ Error occurred in the 1st layer.
Caused by error in `value[[1L]]`:
! subscript out of bounds
```

If the values of `y` are different, or with `method=swarm`, the plot can be completed.
```
mpg %>% ggplot() + geom_beeswarm(aes(x=class, y=cty), method='center')
```
![image|w=60%](https://user-images.githubusercontent.com/46880012/234491434-36e73db3-0e3d-4ac0-b40d-09ff38e41f80.png)

```
mpg %>% mutate(cty=20) %>% ggplot() + geom_beeswarm(aes(x=class, y=cty), method='swarm')
```
![image](https://user-images.githubusercontent.com/46880012/234491659-40fc456d-105d-4f9c-8b85-9c0ccab09a52.png)

**Comment by csdaw** [comment]
Thanks for the reproducible example. I can see this is bug caused by assuming the y values will always have a valid range.
I'll try and fix it.
